### PR TITLE
[Migration][Grid-Marquee] Ported over a new block

### PR DESCRIPTION
**Pull request by JingleH**
Porting the new block into express-milo.

Resolves: https://jira.corp.adobe.com/browse/MWPW-158249

Test URLs:
- Pre Migration Link: https://main--express--adobecom.hlx.live/?martech=off&gnav=off
- Before: https://main--express-milo--adobecom.hlx.live/e?martech=off&gnav=off
- After: https://grid-marquee--express-milo--adobecom.hlx.live/?martech=off&gnav=off

### CODE REVIEW

**Review by vhargrave — COMMENTED** [review]
Looking really good!
The only things I noticed are that the linters are failing and that the mobile view doesn't look quite right because the ratings aren't filling up the space properly. 
image

**Comment by JingleH** [comment]
@vhargrave good catch sir! I've updated everything now. There is 1 remaining mysterious lint issue with make-a-project, but I assume that will be taken care of separately outside this PR right?

**Comment by vhargrave** [comment]
> @vhargrave good catch sir! I've updated everything now. There is 1 remaining mysterious lint issue with make-a-project, but I assume that will be taken care of separately outside this PR right?

@JingleH yes! 
I've just merged in the latest version of `main` here to fix the linters, and now I'm seeing there are just a few tests for this block that are failing. Then I think we're good to go.

**Comment by JingleH** [comment]
Yeah Milo converts links to videos automatically so the html needs to be different. But @vhargrave should be all green now!

**Pull request merged**
