### PR TITLE
Browse By Category Block

### PR DESCRIPTION
**Pull request by echen-adobe**
Adds in the browse by category block, which reads from a list of links and returns a carousel

Express: https://www.adobe.com/express/collections/birthday
After: https://browse-by-category-clean--express-milo--adobecom.hlx.page/express/collections/birthday

### CODE REVIEW

**Comment by vhargrave** [comment]
looks very good! 
the only thing missing is the View All link in the top right corner
image

**Comment by vhargrave** [comment]
> > looks very good! the only thing missing is the View All link in the top right corner
> 
> Found the issue, our old code was looking for a button that was transformed from a link, but this doesn't happen in Milo now, probably because of the different way it handles buttons. Is the button replacement logic expected to change in the future?

yes, the old button logic is only called on a block level now. If that's the only place expecting a button in the file you can update the code to now just expect a link.  
Otherwise it might be easier to just call decorateButtonsDeprecated at the very beginning of your block init method.

**Comment by echen-adobe** [comment]
> Collaborator

Didn't know about the depreciated method, had already changed it to accept the new Milo format, but will keep it in mind for the future

**Comment by vhargrave** [comment]
Just get your tests working & then I think we're good to merge.

**Pull request merged**
