### PR TITLE
Homepage Cards Port

### PR DESCRIPTION
**Pull request by jsandland**
Port the Homepage Cards: GenAI and Discover Cards UI elements from Express to Milo
Authoring Changes Requested By Ernest: https://jira.corp.adobe.com/browse/MWPW-161344?filter=-1
Resolves: [MWPW-158262](https://jira.corp.adobe.com/browse/MWPW-158262)

Test URLs:
- Pre Migration Link: https://adobe.com/express/
- Before: https://main--express-milo--adobecom.hlx.page/express/
- After: https://homepage-cards-port--express-milo--adobecom.hlx.page/drafts/jsandlan/homepage-milo

### CODE REVIEW

**Comment by fullcolorcoder** [comment]
Did you test this out before opening this PR? 
This code doesn't impact the page, and isn't explained.

**Review by fullcolorcoder — CHANGES_REQUESTED** [review]
Not sure where content-cards come from...

**Comment by jsandland** [comment]
This code has been tested on the `milo-express` repo

**Comment by fullcolorcoder** [comment]
@jsandland 

> This code has been tested on the `express-milo` repo

I see you changed the before/after url in the description. 

Are these authoring changes that are coming down the line? As the component is authored today, live on production, your code has no impact. 

image

**Comment by jsandland** [comment]
Ernest requested these authoring changes: https://jira.corp.adobe.com/browse/MWPW-161344?filter=-1

**Comment by fullcolorcoder** [comment]
@jsandland Thanks for the updated context, that makes this PR more reviewable. Before diving into the code I tested it out quick, and I see some immediate differences I'd like you to take a look at. Were there design changes to the design expectations that aren't reflected in that ticket? 

image

**Comment by jsandland** [comment]
@fullcolorcoder Changes ready.

**Review by fullcolorcoder — APPROVED** [review]
Thanks for the updates.

**Pull request merged**
