### PR TITLE
[Migration] Banner cool variant

### PR DESCRIPTION
**Pull request by kennethlum**
Migrate Banner cool variant from Express to Milo Express.

Resolves: [MWPW-158291](https://jira.corp.adobe.com/browse/MWPW-158291)

Test URLs:
- Pre Migration Link: https://adobe.com/express/
- Before: https://banner-cool-variant-before--express-milo--adobecom.hlx.page/docs/library/kitchen-sink/banner
- After: https://banner-cool-variant-after--express-milo--adobecom.hlx.page/docs/library/kitchen-sink/banner

### CODE REVIEW

**Comment by vhargrave** [comment]
This looks really good @kennethlum !
QQ, is there a page where this is also being used live? If so could you provide test links so we can also test that there?

**Comment by kennethlum** [comment]
Hi Victor!  How about this one https://banner-cool-variant-after--express-milo--adobecom.hlx.page/docs/library/kitchen-sink/banner
But do you mean you'd like to see one on express-milo--adobecom.hlx.live instead?

**Review by fullcolorcoder — APPROVED** [review]
Looks cool to me.

**Comment by vhargrave** [comment]
> Hi Victor! How about this one https://banner-cool-variant-after--express-milo--adobecom.hlx.page/docs/library/kitchen-sink/banner But do you mean you'd like to see one on express-milo--adobecom.hlx.live instead?

@kennethlum I meant seeing the banner on a live page, for example this one 
https://banner-cool-variant-after--express-milo--adobecom.hlx.page/express/

**Review by vhargrave — APPROVED** [review]

**Pull request merged**
